### ISSUE TITLE
BRD app main branch is missing WalletKit

### ISSUE THREAD

**Issue by adamdahan** [blockset-corp/walletkit#197]
Hi, 

I am trying to build the BRD app locally onto my iPhone it says that is missing "WalletKit". They don't see to be responding over there. Wonder if you might have some pointers. Just looking for a simple URL to download via Swift PM or a link to some basic install instructions that work. 

Thanks

**Comment by adamdahan** [comment]
Can't seem to run the WalletKitDemo either. https://github.com/blockset-corp/walletkit/issues/198

**Comment by ewerx** [comment]
You need to run `git submodule update --init --recursive` in both cases, as mentioned in the readmes.

**Comment by madeofmoney** [comment]
@ewerx thanks again!

**Comment by adamdahan** [comment]
@ewerx This is why it doesn't work: https://github.com/breadwallet/breadwallet-ios/pull/120
