### ISSUE TITLE
Failed to compile - secp256k1 file not found

### ISSUE THREAD

**Issue by dabitdev** [blockset-corp/walletkit#286]
wallet-kit/walletkit/WalletKitCore/src/support/BRKey.c:52:10: fatal error: 'secp256k1/src/basic-config.h' file not found

these two include are not working
#include "secp256k1/src/basic-config.h"
#include "secp256k1/src/secp256k1.c"

**Comment by dabitdev** [comment]
nevermind, for other users you must go to the main project directory and setup the submodules

git submodule init
git submodule update

**Comment by DrewCarlson** [comment]
secp256k1 is a git submodule, ensure you've run `git submodule update --init --recursive` before compiling.
