### ISSUE TITLE
Flutter / Dart Implementation

### ISSUE THREAD

**Issue by marcellodesales** [blockset-corp/walletkit#351]
Do you guys have a Flutter version?

Instead of separate code for Android/IOS, everything could be integrated ...

**Comment by EBGToo** [comment]
No Flutter version.  WalletKit does not do UI, except for our Demo Apps.  There is Kotlin Multiplatform which might be a viable alternative to eliminating the Swift/Java interfaces.

**Comment by marcellodesales** [comment]
Sounds good... Flutter/dart also eliminates :) 

Kotlin is cool, not sure how big the community is for `IOS/Android/PWA`
