### ISSUE TITLE
Blockchain Wallet and contract data

### ISSUE THREAD

**Issue by MyNicZ** [blockset-corp/walletkit#63]
Web and Wallet kit to run with MyNicZ and Bitcoins.io and Pax Contracts giving transparency reports of proof of ownership and custodial assets.

**Comment by EBGToo** [comment]
Can you explain the issue/need in more detail?

**Comment by dahuisong** [comment]
> Web and Wallet kit to run with MyNicZ and Bitcoins.io and Pax Contracts giving transparency reports of proof of ownership and custodial assets.
